// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqjxbucslgthoobgzobj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxanhidWNzbGd0aG9vYmd6b2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjIzODgsImV4cCI6MjA2NTUzODM4OH0.JWvdLrMzkKhl4-6NExvVVm1ulPO_P2ZuaSIePHuLQIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);